<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Akademik</name>
   <tag></tag>
   <elementGuidId>6c00818f-d275-4ad0-b6d4-2d058b42a237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-745 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-745']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8987b4f0-566c-41a0-9efe-daa8af3277f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>952c5847-be3b-443e-9605-8546d94c824b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akademik</value>
      <webElementGuid>764821b7-3616-46e6-839a-c12bc556fead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-menu&quot;)/li[@id=&quot;menu-item-745&quot;]/a[1]</value>
      <webElementGuid>52dadffc-7263-4dd9-adb5-e403b256c8a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-745']/a</value>
      <webElementGuid>c8c741bb-8b7d-46e9-bc27-0c2ec9d890d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Akademik')]</value>
      <webElementGuid>e46901a5-26cc-4302-9f9f-59415cc4afa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identitas Visual'])[1]/following::a[1]</value>
      <webElementGuid>71d36c30-d9ef-43c9-8c10-c63c5eab62c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluarga Alumni Duta Wacana (KADUWA)'])[1]/following::a[2]</value>
      <webElementGuid>e4640091-7526-43cd-b625-4fd3d3c5c9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fakultas Teologi'])[1]/preceding::a[1]</value>
      <webElementGuid>01aea0b6-6a42-49dd-8989-e535b4cf084f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sarjana Filsafat Keilahian'])[1]/preceding::a[3]</value>
      <webElementGuid>ed13659c-4856-4cac-816f-9fdfda4870e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akademik']/parent::*</value>
      <webElementGuid>9bb4a820-7758-483b-b19a-d6fa854e793f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>bd9f10c2-0d08-448d-94b5-26bd872a89e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>e3dc1100-fbd7-497d-806f-36624f9bce66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Akademik' or . = 'Akademik')]</value>
      <webElementGuid>5658481c-4d64-4e44-aa55-434bc6bcabae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
