<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sistem Informasi</name>
   <tag></tag>
   <elementGuidId>dd4083f5-8899-4348-9933-d14707f98792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-25814 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-25814']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3fda69e4-c720-4df3-8c12-d63778cf05f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ukdw.ac.id/akademik/fakultas-teknologi-informasi/sistem-informasi/</value>
      <webElementGuid>18f7bc1c-4413-4d41-a107-e1008abcffff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sistem Informasi</value>
      <webElementGuid>efa02523-9ee7-4bde-832e-4dcd213273bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-menu&quot;)/li[@id=&quot;menu-item-745&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@id=&quot;menu-item-798&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@id=&quot;menu-item-804&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@id=&quot;menu-item-25814&quot;]/a[1]</value>
      <webElementGuid>3883d50d-9bad-4799-9cdf-f08209baa8bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-25814']/a</value>
      <webElementGuid>73c8ddaa-0c06-43f0-9868-52cfc8d62cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sistem Informasi')]</value>
      <webElementGuid>bc51bd46-24b0-42c7-98ce-74fe8f16c093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informatika'])[1]/following::a[1]</value>
      <webElementGuid>3d6ed6a4-2d77-46ee-a237-7fcccb814861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fakultas Teknologi Informasi'])[1]/following::a[3]</value>
      <webElementGuid>c6dcac09-a7e0-430d-a0b4-e5c218d5170d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fakultas Kedokteran'])[1]/preceding::a[1]</value>
      <webElementGuid>d76c81b4-ffac-430f-ab9b-3f52fe76f0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kedokteran'])[1]/preceding::a[3]</value>
      <webElementGuid>5544e241-6c21-493b-a481-b72e0551ee17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sistem Informasi']/parent::*</value>
      <webElementGuid>d63f2d50-e44c-4ffe-95ef-02ecd5f2919b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ukdw.ac.id/akademik/fakultas-teknologi-informasi/sistem-informasi/')]</value>
      <webElementGuid>084c4030-9aaf-4045-96ad-b1ae695285ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[5]/ul/li/ul/li[2]/a</value>
      <webElementGuid>d36db630-9fea-4f8e-bb07-4dbf8b691c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ukdw.ac.id/akademik/fakultas-teknologi-informasi/sistem-informasi/' and (text() = 'Sistem Informasi' or . = 'Sistem Informasi')]</value>
      <webElementGuid>56680f88-2e94-48f0-b330-def71835d0ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
